# Generated by Django 6.0.7 on 2026-07-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellbeingAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("age", models.FloatField(default=20)),
                ("sex", models.FloatField(default=1)),
                ("resilience", models.FloatField(default=50)),
                ("active_coping", models.FloatField(default=3.0)),
                ("planning", models.FloatField(default=3.0)),
                ("positive_reframing", models.FloatField(default=3.0)),
                ("acceptance", models.FloatField(default=3.0)),
                ("self_blame", models.FloatField(default=2.0)),
                ("predicted_wellbeing", models.FloatField()),
            ],
        ),
    ]
